
--FUNCIONARIO 
nome NVARCHAR(30)  NOT NULL
sexo NCHAR(1) NOT NULL
telefone NVARCHAR(11) NOT NULL
cpf NVARCHAR(11) NOT NULL
data_admissao DATE NOT NULL
matricula NVARCHAR(7) NOT NULL
cod_cargo NVARCHAR(4) NOT NULL
cod_departamento NVARCHAR(4) NOT NULL

-- DEPARTAMENTO 
cod_departamento  NVARCHAR(4) NOT NULL
nome_departamento NVARCHAR(12) NOT NULL

-- CARGO 
cod_cargo NVARCHAR(4) NOT NULL
nome_cargo NVARCHAR(12) NOT NULL

-- GERENTE
cod_cargo NCHAR(11) NOT NULL
cod_departamento  NVARCHAR(4) NOT NULL
matricula NVARCHAR(7) NOT NULL
salario FLOAT(8) NOT NULL
vale_alimentacao FLOAT(8) NOT NULL

-- COORDENADOR DE ATENDIMENTO
cod_cargo NCHAR(11) NOT NULL
cod_departamento  NVARCHAR(4) NOT NULL
matricula NVARCHAR(7) NOT NULL
salario FLOAT(8) NOT NULL
gratificacao FLOAT(8) NOT NULL

-- ANALISTA DE CALL CENTER
cod_cargo NCHAR(11) NOT NULL
cod_departamento  NVARCHAR(4) NOT NULL
matricula NVARCHAR(7) NOT NULL
salario FLOAT(8) NOT NULL
especialidade NVARCHAR(12) NOT NULL

-- ATENDENTE DE CALL CENTER   
cod_cargo NCHAR(11) NOT NULL
cod_departamento  NVARCHAR(4) NOT NULL
matricula NVARCHAR(7) NOT NULL
salario FLOAT(8) NOT NULL
hora_extra FLOAT(8) NOT NULL

-- CLIENTE

nome NVARCHAR(30)  NOT NULL
sexo NCHAR(1) NOT NULL
email NVARCHAR NOT NULL
cpf NVARCHAR(11) NOT NULL
cep NVARCHAR(11) NOT NULL
telefone NVARCHAR (3) NOT NULL
cidade NVARCHAR(30) NOT NULL
cod_chamada INT(7) NOT NULL


--RECLAMAÇOES 
cod_departamento  NVARCHAR(4) NOT NULL
id_cliente INT(7) NOT NULL
id_matricula INT(7) NOT NULL
cod_chamada INT(7) NOT NULL
protocolo INT(7) NOT NULL


